
# application-docker.properties
spring.datasource.url=jdbc:postgresql://postgres:5432/inventory
spring.datasource.username=postgres
spring.datasource.password=123456

spring.kafka.consumer.bootstrap-servers=kafka:9092

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
management.security.enabled=false
spring.security.user.name=admin
spring.security.user.password=admin