spring.application.name=historico-service
server.port=8081

# ===============================
# DATABASE
# ===============================

spring.datasource.url=jdbc:postgresql://postgres:5432/inventory
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# JWT
# ===============================

jwt.secret=${JWT_SECRET:minha-chave-dev}
jwt.expiration=3600000

# ===============================
# KAFKA CONSUMER
# ===============================

spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.consumer.group-id=historico-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=com.produtoapi.historicoservice.dto.ProdutoEventoDTO