spring.application.name=produto-service

server.port=8080

jwt.secret=${JWT_SECRET}
jwt.expiration=3600000

spring.jpa.hibernate.ddl-auto=update

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

