
jwt.secret=${JWT_SECRET}
jwt.expiration=3600000
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.application.name=produto-service
spring.datasource.url=jdbc:postgresql://localhost:5432/inventory
spring.datasource.username=postgres
spring.datasource.password=123456
server.port=8080
spring.kafka.producer.properties.spring.json.add.type.headers=true
spring.jpa.hibernate.ddl-auto=update