name: CI Pipeline with Docker and k6

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # JAVA
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      # DOCKER COMPOSE
      - name: Start containers
        run: |
          docker compose -f infra/docker-compose.yml up -d --build

      # ESPERA A API SUBIR
      - name: Wait services startup
        run: sleep 60

      # TESTE LOGIN
      - name: Run Login Load Test
        uses: grafana/setup-k6-action@v1

      - name: Execute Login Test
        run: |
          k6 run infra/k6/login-test.js

      # TESTE POST PRODUTO
      - name: Execute Produto POST Test
        run: |
          k6 run infra/k6/produto-post-test.js

      # TESTE GET PRODUTOS
      - name: Execute Produto GET Test
        run: |
          k6 run infra/k6/produto-get-test.js

      # LOGS CASO FALHE
      - name: Show container logs
        if: failure()
        run: |
          docker compose -f infra/docker-compose.yml logs

      # FINALIZA CONTAINERS
      - name: Stop containers
        if: always()
        run: |
          docker compose -f infra/docker-compose.yml down
